name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Download and Prepare Skia
      shell: bash
      run: |
        # 使用 curl 下载 Skia 预编译包
        curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip
        # 显式解压到当前目录下的 skia 文件夹
        7z x skia.zip -oskia -y

    - name: Run CMake Configuration
      shell: bash
      run: |
        mkdir build
        # 注意：这里使用了相对路径引用刚才解压的 skia 文件夹
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_UI=ON \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$(pwd)/skia \
          -DSKIA_LIBRARY_DIR=$(pwd)/skia/out/Release-x64 \
          -DSKIA_LIBRARY=$(pwd)/skia/out/Release-x64/skia.lib

    - name: Build Aseprite
      shell: bash
      run: |
        cd build
        ninja aseprite

    - name: Upload Finished Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-build
        path: |
          build/bin/data
          build/bin/aseprite.exe
